project:
  title: "trabajo_BigData"

#- para incluir el logo de la UV en la pestaña del navegador
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "imagenes/uv.jpeg" />
     
#- hace el rendered documento (.html) autocontenido  
embed-resources: true  

#- anchor sections (links en las secciones del rendered document)
anchor-sections: true

#- otros enlaces (que aparecerán debajo del TOC)
other-links:
  - text: Web del curso
    href: https://perezp44.github.io/intro-ds-24-25-web/
  - text: Trabajos de mis compañeros
    href: https://perezp44.github.io/intro-ds-24-25-web/05-trabajos-estudiantes.html 
  - text: Repo del trabajo
    #- has de cambiar "perezp44" por tu usuario de Github
    href: https://github.com/estebanpardo50/trabajo_BigData
  
#- opciones para el índice (TOC)
toc: true
toc-depth: 3
toc-location: left    

#- hace que los links se abren en pestañas nuevas
link-external-newwindow: true 

#- Cross-references
crossref:
  fig-title: Gráfico  # (default is "Figure")
  tbl-title: Tabla    # (default is "Table")
  #title-delim: —     # (default is ":")

#- Posicion de los fig-captions
fig-cap-location: bottom

#- opciones para las imágenes hechas con código   
#fig-height: 5
fig-width: 7
fig.asp: 0.68
fig-format: png
fig-dpi: 90


#- opciones para los chunks de código --
#- https://quarto.org/docs/output-formats/html-code.html
code-copy: true
code-overflow: wrap   
code-fold: show
code-line-numbers: true

#- embeed the source document
code-tools: true
code-link: true

# Default execute options
execute:
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
  echo: true
  eval: true
  message: false
  warning: false

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  

#- el output de los chunks del .qmd van a los panes
editor_options: 
  chunk_output_type: console

#- licencia: https://quarto.org/docs/reference/formats/html.html#metadata
license: CC BY

#- opciones de lenguaje
lang: es  #- castellano {es, en}
language: assets/_my_language-es.yml


# comments:
#   hypothesis: 
#     theme: clean

#- para compartir en redes sociales
#- has de sustituir "perezp44" por tu usuario de Github
# filters:
#   - social-share
#   
# share:
#   permalink: "https://alexboix12.github.io/trabajo_BidData/"
#   description: "Este es el trabajo que hemos hecho para la asignatura de BigData!! Échale un vistazo!!" 
#   twitter: true
#   linkedin: true
#   email: true
